#!/usr/bin/env python3

"""
Defines constants used in naming each node.
"""

CLARIUS_US_PUBLISHER: str = 'ClariusPublisher'
CLARIUS_US_SPOOF: str = 'ClariusSpoof'
IMAGE_DATA_CONVERTER: str = 'ImageDataConverter'
IMAGE_CONTACT_BALANCING: str = 'ImageContactBalancing'
IMAGE_BASED_USER_INPUT: str = 'ImageBasedUserInput'
REAL_TIME_IMAGE_FILTER: str = 'RealTimeImageFilter'
VISUALIZER: str = 'Visualizer'
IMAGE_POSITIONING_CONTROLLER: str = 'ImagePositioningController'
IMAGE_POSITION_REGISTRATION: str = 'ImagePositionRegistration'
NON_REAL_TIME_IMAGE_FILTER: str = 'NonRealTimeImageFilter'
VOLUME_GENERATION: str = 'VolumeGeneration'

TRANSFORMATION_CREATION: str = 'TransformationCreation'
TRAJECTORY_MANAGEMENT: str = 'TrajectoryManagement'
ROBOT_CONTROL: str = 'RobotControl'

CONTROLLER_TUNING_GRAPHS: str = 'ControllerTuningGraphs'

EXPERIMENT_DATA_RECORDER: str = 'ExperimentDataRecorder'
EXPERIMENT_NOISE_MAKER: str = 'ExperimentNoiseMaker'

USER_INTERFACE: str = 'UserInterface'

HIGH_LEVEL_MOTION_CONTROLLER: str = 'HighLevelMotionController'

ALL_NAMES: tuple = (CLARIUS_US_PUBLISHER, CLARIUS_US_SPOOF, IMAGE_DATA_CONVERTER, IMAGE_CONTACT_BALANCING,
                    IMAGE_BASED_USER_INPUT, REAL_TIME_IMAGE_FILTER, VISUALIZER, IMAGE_POSITIONING_CONTROLLER,
                    IMAGE_POSITION_REGISTRATION, NON_REAL_TIME_IMAGE_FILTER, VOLUME_GENERATION,
                    TRANSFORMATION_CREATION, TRAJECTORY_MANAGEMENT, ROBOT_CONTROL,
                    CONTROLLER_TUNING_GRAPHS, EXPERIMENT_DATA_RECORDER, USER_INTERFACE)

CORE_NAMES: tuple = (IMAGE_CONTACT_BALANCING,IMAGE_BASED_USER_INPUT,
                     REAL_TIME_IMAGE_FILTER, VISUALIZER, IMAGE_POSITIONING_CONTROLLER,
                     IMAGE_POSITION_REGISTRATION, NON_REAL_TIME_IMAGE_FILTER, VOLUME_GENERATION,
                     TRAJECTORY_MANAGEMENT, ROBOT_CONTROL, USER_INTERFACE)
